from __future__ import annotations

"""Default permissions assigned when accepting an invitation for a given role."""

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "owner": [
        "dashboard.read",
        "ai.copilot.use",
        "ai.agent.use",
        "crm.contact.read",
        "crm.contact.write",
        "crm.lead.read",
        "crm.lead.write",
        "finance.invoice.read",
        "finance.invoice.write",
        "task.read",
        "task.write",
        "support.ticket.read",
        "support.ticket.write",
        "document.read",
        "document.write",
        "workflow.read",
        "workflow.write",
        "settings.org",
        "settings.team",
        "settings.billing",
        "admin.audit",
        "admin.flags",
        "analytics.read",
        "bi.read",
    ],
    "admin": [
        "dashboard.read",
        "ai.copilot.use",
        "crm.contact.read",
        "crm.contact.write",
        "crm.lead.read",
        "crm.lead.write",
        "finance.invoice.read",
        "finance.invoice.write",
        "task.read",
        "task.write",
        "support.ticket.read",
        "support.ticket.write",
        "document.read",
        "document.write",
        "workflow.read",
        "workflow.write",
        "settings.org",
        "settings.team",
        "admin.flags",
        "analytics.read",
        "bi.read",
    ],
    "sales_manager": [
        "dashboard.read",
        "ai.copilot.use",
        "crm.contact.read",
        "crm.contact.write",
        "crm.lead.read",
        "crm.lead.write",
        "task.read",
        "task.write",
        "document.read",
    ],
    "finance_manager": [
        "dashboard.read",
        "finance.invoice.read",
        "finance.invoice.write",
        "task.read",
        "document.read",
        "bi.read",
    ],
    "hr_manager": [
        "dashboard.read",
        "task.read",
        "task.write",
        "document.read",
        "support.ticket.read",
    ],
    "staff": [
        "dashboard.read",
        "task.read",
        "task.write",
        "document.read",
        "crm.contact.read",
        "crm.lead.read",
        "finance.invoice.read",
        "support.ticket.read",
    ],
    "viewer": [
        "dashboard.read",
        "crm.contact.read",
        "crm.lead.read",
        "finance.invoice.read",
        "task.read",
        "document.read",
    ],
    "project_manager": [
        "dashboard.read",
        "task.read",
        "task.write",
        "document.read",
        "document.write",
        "crm.contact.read",
    ],
}

INVITABLE_ROLES = sorted(set(ROLE_PERMISSIONS.keys()) - {"owner"})


def permissions_for_role(role: str) -> list[str]:
    return list(ROLE_PERMISSIONS.get(role, ROLE_PERMISSIONS["staff"]))
