from __future__ import annotations

"""Default permissions assigned when accepting an invitation for a given role."""

# Full product catalog — keep aligned with frontend APP_PERMISSIONS / navigation.
OWNER_PERMISSIONS: list[str] = [
    "dashboard.read",
    "ai.copilot.use",
    "ai.agent.use",
    "ai.approval.decide",
    "crm.contact.read",
    "crm.contact.write",
    "crm.lead.read",
    "crm.lead.write",
    "sales.order.read",
    "sales.order.write",
    "marketing.campaign.read",
    "marketing.campaign.write",
    "finance.invoice.read",
    "finance.invoice.write",
    "finance.payment.read",
    "finance.payment.write",
    "project.read",
    "project.write",
    "task.read",
    "task.write",
    "calendar.read",
    "calendar.write",
    "meeting.read",
    "meeting.write",
    "document.read",
    "document.write",
    "inventory.read",
    "inventory.write",
    "hr.employee.read",
    "hr.employee.write",
    "hr.recruitment.read",
    "hr.recruitment.write",
    "hr.leave.read",
    "hr.leave.write",
    "support.ticket.read",
    "support.ticket.write",
    "contract.read",
    "contract.write",
    "knowledge.read",
    "knowledge.write",
    "analytics.read",
    "bi.read",
    "ml.forecast.read",
    "workflow.read",
    "workflow.write",
    "settings.profile",
    "settings.org",
    "settings.team",
    "settings.billing",
    "admin.audit",
    "admin.flags",
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "owner": list(OWNER_PERMISSIONS),
    "admin": [
        "dashboard.read",
        "ai.copilot.use",
        "ai.agent.use",
        "ai.approval.decide",
        "crm.contact.read",
        "crm.contact.write",
        "crm.lead.read",
        "crm.lead.write",
        "sales.order.read",
        "marketing.campaign.read",
        "finance.invoice.read",
        "finance.invoice.write",
        "finance.payment.read",
        "project.read",
        "project.write",
        "task.read",
        "task.write",
        "calendar.read",
        "meeting.read",
        "document.read",
        "document.write",
        "inventory.read",
        "hr.employee.read",
        "hr.recruitment.read",
        "hr.leave.read",
        "support.ticket.read",
        "support.ticket.write",
        "contract.read",
        "knowledge.read",
        "workflow.read",
        "workflow.write",
        "settings.org",
        "settings.team",
        "settings.profile",
        "admin.flags",
        "analytics.read",
        "bi.read",
        "ml.forecast.read",
    ],
    "sales_manager": [
        "dashboard.read",
        "ai.copilot.use",
        "crm.contact.read",
        "crm.contact.write",
        "crm.lead.read",
        "crm.lead.write",
        "sales.order.read",
        "sales.order.write",
        "marketing.campaign.read",
        "task.read",
        "task.write",
        "document.read",
        "settings.profile",
    ],
    "finance_manager": [
        "dashboard.read",
        "finance.invoice.read",
        "finance.invoice.write",
        "finance.payment.read",
        "task.read",
        "document.read",
        "bi.read",
        "analytics.read",
        "ml.forecast.read",
        "settings.profile",
    ],
    "hr_manager": [
        "dashboard.read",
        "task.read",
        "task.write",
        "document.read",
        "hr.employee.read",
        "hr.employee.write",
        "hr.recruitment.read",
        "hr.recruitment.write",
        "hr.leave.read",
        "hr.leave.write",
        "support.ticket.read",
        "settings.profile",
    ],
    "staff": [
        "dashboard.read",
        "task.read",
        "task.write",
        "document.read",
        "crm.contact.read",
        "crm.lead.read",
        "finance.invoice.read",
        "support.ticket.read",
        "calendar.read",
        "meeting.read",
        "knowledge.read",
        "settings.profile",
    ],
    "viewer": [
        "dashboard.read",
        "crm.contact.read",
        "crm.lead.read",
        "finance.invoice.read",
        "task.read",
        "document.read",
        "settings.profile",
    ],
    "project_manager": [
        "dashboard.read",
        "task.read",
        "task.write",
        "project.read",
        "project.write",
        "document.read",
        "document.write",
        "crm.contact.read",
        "calendar.read",
        "meeting.read",
        "settings.profile",
    ],
}

INVITABLE_ROLES = sorted(set(ROLE_PERMISSIONS.keys()) - {"owner"})


def permissions_for_role(role: str) -> list[str]:
    return list(ROLE_PERMISSIONS.get(role, ROLE_PERMISSIONS["staff"]))
